---
 - name: instalación sshpass y python-minimal "{{lxc_name}}"
   lxc_container:
     name: "{{lxc_name}}"
     container_command: apt update && apt install sshpass  python-minimal -y

 - name: instalación sudo "{{lxc_name}}"
   lxc_container:
     name: "{{lxc_name}}"
     container_command: |
       apt install sudo -y

 - name: creación de usuario
   lxc_container:
     name: "{{lxc_name}}"
     container_command: useradd usuario -s /bin/bash -m 

 - name: configuración del usuario
   lxc_container:
     name: "{{lxc_name}}"
     container_command: |
        echo -e "usuario\nusuario" | passwd usuario

 - name: configuración de sudo
   lxc_container:
     name: "{{lxc_name}}"
     container_command: |
        echo "usuario ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
       
