<?php
$version = 'v1.6.17';
$pagedata = array(
    'default' => array(
        'title_1' => 'Actividad 24x7',
        'description' => '',
        'filename' => 'actividad.php',
        'admin' => 0),
    'grupo' => array(
        'title_1' => 'Grupos',
        'description' => '',
        'filename' => 'grupo.php',
        'admin' => 1),
    'tecnico' => array(
        'title_1' => 'Tecnicos',
        'description' => '',
        'filename' => 'tecnico.php',
        'admin' => 0),
    'proyecto' => array(
        'title_1' => 'Proyectos',
        'description' => '',
        'filename' => 'proyecto.php',
        'admin' => 1),
    /* 'tarea' => array(
        'title_1' => 'Tareas',
        'description' => '',
        'filename' => 'tarea.php',
        'admin' => 1),
    'subtarea' => array(
        'title_1' => 'Subtareas',
        'description' => '',
        'filename' => 'subtarea.php',
        'admin' => 1), */
    'tipo_evento' => array(
        'title_1' => 'Tipos de Evento',
        'description' => '',
        'filename' => 'tipo_evento.php',
        'admin' => 1),
    /* 'procedimiento' => array(
        'title_1' => 'Procedimientos',
        'description' => '',
        'filename' => 'procedimiento.php',
        'admin' => 1), */
    'tipo_estado' => array(
        'title_1' => 'Tipos de Estado',
        'description' => '',
        'filename' => 'tipo_estado.php',
        'admin' => 1),
    'parametro' => array(
	'title_1' => 'Parametros',
	'description' => '',
	'filename' => 'parametro.php',
	'admin' => 1),
    'parametro1' => array(
        'title_1' => 'Parametros 1',
        'description' => '',
        'filename' => 'parametro1.php',
        'admin' => 1),
    'parametro2' => array(
        'title_1' => 'Parametros 2',
        'description' => '',
        'filename' => 'parametro2.php',
        'admin' => 1),
    );
?>
