---

 - name: instalacin de python-mysqlb 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
       apt install python-mysqldb -y

 - name: instalacin de mysql-server 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
       apt install mysql-server -y

 - name: Copiar la configuracion
   copy: src=my.cnf dest=/var/lib/lxc/{{lxc_name}}/rootfs/etc/mysql/my.cnf

   
 - name: Reiniciando MySQL 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
       /etc/init.d/mysqld restart
