---
- name: Creación del contenedor "{{lxc_name}}" 
  lxc_container:
    name: "{{ lxc_name }}"
    container_log: true
    template: debian
    state: stopped
    template_options: --release jessie

 - name: configurando red de "{{ lxc_name }}"
   template: 
     src: roles/lxc/files/config
     dest: /var/lib/lxc/"{{lxc_name}}"/config
     owner: root
     group: root
     mode: 0644

 - name: Levantando "{{ lxc_name }}"
   lxc_container:
     name: "{{ lxc_name }}"
     state: started
