---
    
 - name: instalación de bind9 (DNS) 
   lxc_container: 
     name:"{{lxc_name}}"
     container_command:apt update && apt install bind9 -y



 - name: configurando zona directa
   template: 
     src: roles/dns/files/db.arodriguez
     dest: /var/lib/lxc/"{{lxc_name}}"/rootfs/var/cache/bind/db.arodriguez
     owner: root
     group: root
     mode: 0644

 - name: configurando conf.local
   template:
     src: roles/dns/files/db.named.conf.local
     dest: /var/lib/lxc/"{{lxc_name}}"/rootfs/etc/bind/named.conf.local
     owner: root
     group: root
     mode: 0644


 - name: configurando zona inversa
   template:
     src: roles/dns/files/db.10.0.4
     dest: /var/lib/lxc/"{{lxc_name}}"/rootfs/var/cache/bind/db.10.0.4
     owner: root
     group: root
     mode: 0644       

       
 - name: Reinicio del DNS
   lxc_container: 
     name:"{{lxc_name}}"
     container_command:systemctl restart bind9
       
       
       
