---

 - name: instalación de apache2 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
       apt install apache2 -y
       
 - name: instalación de php 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
        apt install php -y

 - name: Reiniciando apache 
   lxc_container: 
     name: "{{lxc_name}}"
     container_command:  |
       apachectl restart
       
