---
 - name: instalaci칩n de httpd (apache)
   apt: name=apache2 state=present

 - name: instalaci칩n de php
   apt: name=php state=present

 - name: Copiar la p치gina de presentaci칩n
   copy: src=index.html dest=/var/www/html/index.html 

 - name: reinicio de http
   service:
     name: apache2
     state: restarted
